### ISSUE TITLE
How to build embedding?

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#468]
## ❓ Questions and Help

I see Vocab is built as part of the Dataset in [build_vocab](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/data/dataset.py#L713). I also see VocabModel is building embedding [randomly](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/utils/vocab_utils.py#L123) if no pre-trained embedding is passed.

I have a few questions:

- **Q1:** Can I learn word embedding (like `word2vec`) as part of the training? If yes, can you refer to an example, please?

- **Q2.** I am confused about the following section:

```
    embedding_style:
      single_token_item: true
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null
```

Is this section only relevant for the dynamic graph?

- **Q3.** As part of the topology construction `embedding_style` is passed. What is its role?
