### ISSUE TITLE
Description of the configuration file

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#493]
## ❓ Questions and Help

I am finding the configuration file confusing. Also, I don't find any documentation for it either. As an example:

### **graph_construction_args**:
- It has three sections: `graph_construction_share`, `graph_construction_private`, and `node_embedding`. Why two section i.e., `graph_construction_share` and `graph_construction_private`. What this `share` and `private` is for?

```
graph_construction_args:
  graph_construction_share:
    graph_type: 'dependency'
    root_dir: "model-artifacts/data"
    topology_subdir: 'NodeEmbGraph'
    share_vocab: false
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false

  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: true
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 2
      bert_model_name: null
      bert_lower_case: null

    sim_metric_type: 'weighted_cosine'
    num_heads: 1
    top_k_neigh: null
    epsilon_neigh: 0.5
    smoothness_ratio: 0.1
    connectivity_ratio: 0.05
    sparsity_ratio: 0.1```
```

### **Embedding**

`node_embedding` was already defined as part of the `graph_construction_args`. Then there is another `graph_embedding_args`. Why embedding is in two places i.e. as part of the `graph_construction_args` and here `graph_embedding_args` again?  Furthermore, it has this share and private section. Can you please help me understand why is this separation and for what purpose.

```
graph_embedding_args:
  graph_embedding_share:
    num_layers: 2
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "undirected"
    feat_drop: 0.0

  graph_embedding_private:
    heads: [1, 1]
    attn_drop: 0.0
    negative_slope: 0.2
    residual: false
    activation: null
    allow_zero_in_degree: false
```

### **decoder_args**
- It has two sections: `rnn_decoder_share`, `rnn_decoder_private`. What is the difference between ` rnn_decoder_share` and `rnn_decoder_private` and why they are separate.

```
decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: false
    use_coverage: false
    graph_pooling_strategy: "max"
    attention_type: "sep_diff_encoder_type" # "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 50
    node_type_num: null
    tgt_emb_as_output_layer: false
```
