### ISSUE TITLE
How to set vocab size?

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#495]
## ❓ Questions and Help

I see I can set the vocab size while building the VocabModel. 

But can we set it from config files? I have already looked into the configuration files. However, I do not see vocab size to be configurable. 

Can you please clarify?

**Comment by nashid** [comment]
@AlanSwift can you provide any pointers, please?

**Comment by AlanSwift** [comment]
This is an example: [QG vocab size](https://github.com/graph4ai/graph4nlp/blob/e7ad93f590b9399034d3ebfbd857cc5a4de977f0/examples/pytorch/question_generation/config/squad_split2/qg.yaml#L8).

**Comment by nashid** [comment]
Thanks, @AlanSwift for pointing out:

```
# Preprocessing
top_word_vocab: 70000
share_vocab: True
word_emb_size: 300
min_word_freq: 1
num_hidden: 300 # number of hidden units
n_samples: null
```

But where does it fit for the [NMT example](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/nmt/config/dynamic_gcn.yaml)?

There are two sections here:

```
  graph_construction_share:
    graph_name: 'node_emb'
    root_dir: "examples/pytorch/nmt/data"
    topology_subdir: 'NodeEmbGraph'
    share_vocab: false
    thread_number: 4
    port: 9000
    timeout: 15000
````
  
and
 
```
graph_embedding_args:
  graph_embedding_share:
    num_layers: 3
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_fuse"
    feat_drop: 0.2

  graph_embedding_private:
    gcn_norm: 'both'
    weight: true
    bias: true
    activation: "relu"
    allow_zero_in_degree: false
    use_edge_weight: true
```

I presume it would go as part of the `graph_embedding_args`?

````
graph_embedding_args:
  graph_embedding_share:
    num_layers: 3
    input_size: 300
    hidden_size: 300
    output_size: 300
    direction_option: "bi_fuse"
    feat_drop: 0.2
    top_word_vocab: 70000 <<<
    word_emb_size: 300       <<<
    min_word_freq: 1              <<<

  graph_embedding_private:
    gcn_norm: 'both'
    weight: true
    bias: true
    activation: "relu"
    allow_zero_in_degree: false
    use_edge_weight: true
````
