### ISSUE TITLE
Difference between heterogeneous and as_node

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#529]
## ❓ Questions and Help

I am implementing a heterogeneous graph. 

- However, after following the documentation, `heterogeneous` and `as_node` is not quite clear to me. 

- Secondly, how can I set `edge_attributes` for the `heterogeneous` and `as_node` graphs?

I see following section in the config file:

```
  graph_construction_private:
    edge_strategy: 'heterogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false
```

If in the config file, if I set `as_node: true` and then set `edge_attribute` using the following code snippet, is it enough to implement the `as_node` graph?

```
ret_graph.edge_attributes[edge_idx]["token"] = "some-token"
```

**Comment by AlanSwift** [comment]
Note: The ``heterogeneous`` GNN is not supported. Currently, it is just stored in the graph data. The edge information will be dropped in the pipeline. But ``as_node`` is supported.
For example, node A --edge type C--> node B (node A and node B are connected with edge type C). For the heterogeneous graph type, edge type C is stored in ``edge``. For ``as_node``, edge C is converted into a new node with node value C. And the graph is converted to a levi-graph.
Please refer to our paper: [Graph Neural Networks for Natural Language Processing: A Survey](https://arxiv.org/abs/2106.06090) for more details.

**Comment by nashid** [comment]
@AlanSwift thanks for the pointers. But one thing that is not clear to me is how to create the graph with `as_node`? Is the following code creating a graph with `as-node`?

Lets say `nodeA` is connected to `nodeB` with an edge with `has` token.

```
nodeA --(edge: has)--> nodeB
```

And I do:

```
ret_graph.edge_attributes[edge_idx]["token"] = "has"
```

And I set `as_node: true` in the config:

```
  graph_construction_private:
    edge_strategy: 'heterogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: true
```

Is it creating the `as_node` graph? 

(OR do I have to do it manually?)
