### ISSUE TITLE
Using different GNN for the NMT task

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#530]
## ❓ Questions and Help

I want to use different GNN architecture for the NMT model that is provided. I presume I set the "graph_embedding_name:" to different GNN architectures, i.e.:

- gat 
- graphsage
- ggnn   

And then adjust the `graph_construction_private` values and that would do?

I am particularly interested to run NMT with GAT as that makes more sense as I can use copy mechanism. Of course for my case the input and output has same vocab. Do I have to make any fundamental change to the NMT example already provided? Or would that work as is?

**Comment by AlanSwift** [comment]
You can change GNN to gat, graphsage and ggnn according to your need.

For copy, you have to change the code. Please refer to the [semantic_parsing](https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/semantic_parsing/graph2seq), QG, summarization's implementation.

**Comment by smith-co** [comment]
@AlanSwift For NMT, `GAT with copy mechanism` is very common. All the NMT model like OpenNMT support it. Do you plan to add an example for that, please🙏?

**Comment by smith-co** [comment]
Regarding the number of heads, do you recommend any heuristics regarding how many heads to use?

```
  graph_embedding_private:
    heads: [2, 2, 1]
    attn_drop: 0.2
    negative_slope: 0.2
    residual: true
    activation: "relu"
    allow_zero_in_degree: true
```
