### ISSUE TITLE
using copy mechanism

### ISSUE THREAD

**Issue by code2graph** [graph4ai/graph4nlp#537]
## ❓ Questions and Help

Came across this fantastic library just a week back. This library is looking great 🥇

I will be mostly using the example for **machine translation**. Will also use the **text summarization at a later point.

I am currently using `opennmt` for **machine translation** and use the `copy_mechanism` as my source and target has same vocabulary. Now I will be moving to your library for this `NMT` task so that my input could leverage the graph structure.  

At the same time, I need to use the `copy_mechanism` for OOV issue. My questions:

1. It appears to me, I just need to set the `use_copy` as true for the `decoder_args` and that should do for the `NMT` example. Am I missing something?

```
decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: true
    graph_pooling_strategy: null
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3
```

2. I am using the `Graph2Seq` model as per the `NMT` example. In the NMT example, you have used `GCN`. For the `copy` mechanism to be more effective does it has a relation with what GNN I use? 

You have four GNN models - GCN, GAT, GGNN, GraphSage. Do you think `copy` mechanism would be more effective for a specific GNN? Or it does not matter?

3. Would enabling the copy mechanism lower the accuracy/BLEU score of the translation task?

**Comment by AlanSwift** [comment]
1. The examples are just examples to guide the users, which don't support all functions in our library (And we don't plan to for every application.). The NMT doesn't support copy mechanism since the source and target's vocabularies are different. You have to implement it by yourself. Other applications such as QG, semantic-parsing are examples that support copy.
2. Copy mechanism is a general NLP technique just as GNN is. I think such a conclusion can't be made.
3. For semantic parsing, summarization, question generation applications, copy is relatively useful and can get performance gains, empirically. But I can't promise that it is useful for all applications. I suggest you have a try on your own application and see it's performance.

**Comment by AlanSwift** [comment]
I can share my thoughts if you want to implement copy for NMT.
1. You can read the [semantic parsing](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/semantic_parsing/graph2seq/main.py). This is a good example that shows how copy works.
Also the original paper: [pointer network](https://arxiv.org/abs/1704.04368).
2. You can design the special source and target vocabs. For example, they are 1k words. The source and target's vocabs can be the same in the top 1k words and with different words in the following. And the oov vocabulary can share the top 1k words with the source and target vocabulary.(copy from the top 1k and oov words)

**Comment by code2graph** [comment]
> * Copy mechanism is a general NLP technique just as GNN is. I think such a conclusion can't be made.

@AlanSwift I suppose I have to try out the `copy mechanism` with different GNN and validate it empirically. That's what you meant?

**Comment by nashid** [comment]
@AlanSwift you mentioned:

```
You can design the special source and target vocabs. For example, they are 1k words. The source and target's vocabs can be the same in the top 1k words and with different words in the following. And the oov vocabulary can share the top 1k words with the source and target vocabulary.(copy from the top 1k and oov words)
```

Wondering why you mentioned to use a small vocab of `1k`? Is it better to use small vocab size empirically? Also I suppose I just need to change the config here i.e. 

- graph_embedding_name: "gat"
- top_word_vocab: 1000

```
graph_construction_name: "node_emb"
graph_embedding_name: "gat"
decoder_name: "stdrnn"
checkpoint_save_path: "./model/save"

graph_construction_args:
  graph_construction_share:
    graph_type: 'dependency'
    root_dir: "model-artifacts/"
    topology_subdir: 'NodeEmbGraph'
    top_word_vocab: 1000
    share_vocab: true
```
